import { Resend } from 'resend';
import { ReactElement } from 'react';

// Initialize Resend with API Key from env
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

interface SendEmailParams {
  to: string;
  subject: string;
  text?: string; // Made optional if react is provided
  html?: string;
  react?: ReactElement;
}

/**
 * Sends an email using Resend SDK
 */
export async function sendEmail({ to, subject, text, html, react }: SendEmailParams) {
  // Check if SDK is initialized
  if (!resend) {
    console.log('⚠️ [Resend Service] RESEND_API_KEY not found. Email not sent, but logged to console.');
    console.log(`To: ${to}`);
    console.log(`Subject: ${subject}`);
    if (text) console.log(`Content: ${text}`);
    if (react) console.log(`[React Component Provided for Email Content]`);
    return { success: true, logged: true };
  }

  try {
    const { data, error } = await resend.emails.send({
      from: process.env.EMAIL_FROM || 'FIX-AI <onboarding@resend.dev>',
      to: [to],
      subject: subject,
      text: text || '', // Fallback text if using react is auto-generated by Resend usually, but good to have
      html: html,
      react: react,
    });

    if (error) {
      console.error('❌ [Resend Service] API Error:', error);
      return { success: false, error };
    }

    console.log('✅ [Resend Service] Email sent successfully:', data?.id);
    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error('❌ [Resend Service] Unexpected Error:', error);
    return { success: false, error };
  }
}
